# This workflow is the main workflow on pushing to the main branch
# and runs builds, releases, conventional commits, and pushes.

name: Main

on:
  push:
    branches: [main]

jobs:
  build-java:
    uses: ./.github/workflows/build-java.yml
    with:
      tagTypes: |
        type=sha

  release:
    runs-on: ubuntu-latest
    needs: [build-java]
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Checkout code with commit history
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --save-dev @semantic-release/changelog@6.0.3 @semantic-release/git@10.0.1 @semantic-release/exec@6.0.3 conventional-changelog-conventionalcommits@7.0.2
      - name: Create GitHub App token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        id: app-token
        with:
          app-id: ${{ vars.SEMANTIC_RELEASE_GH_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_GH_APP_PRIVATE_KEY }}
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: npx semantic-release@23.0.7

  publish-image:
    uses: ./.github/workflows/build-java.yml
    needs: release
    if: needs.release.outputs.version != ''
    with:
      tagTypes: |
        type=semver,pattern={{version}},value=${{ needs.release.outputs.version }}
        type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
