# This workflow is the main workflow on pushing to the main branch
# and runs builds, releases using semantic release and bot to push changes, conventional commits, and pushes.

name: Main

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  build-node:
    uses: ./.github/workflows/build-node.yml

  build-image:
    uses: ./.github/workflows/build-image.yml
    needs: build-node
    with:
      tagTypes: |
        type=sha

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor          

  release:
    runs-on: ubuntu-latest
    needs: [build-image, snyk]
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Checkout code with commit history
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1
        id: app-token
        with:
          app-id: ${{ vars.SEMANTIC_RELEASE_GH_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_GH_APP_PRIVATE_KEY }}
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: npx semantic-release@23.0.7

  publish-image:
    uses: ./.github/workflows/build-image.yml
    needs: release
    if: needs.release.outputs.version != ''
    with:
      tagTypes: |
        type=semver,pattern={{version}},value=${{ needs.release.outputs.version }}
        type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
