name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JARS
        run: |
          cd dks-api && ./gradlew bootJar
          cd ../dks-ui && ./gradlew bootJar

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
         docker compose build
         docker tag dks-api:latest ghcr.io/langbledsoe/dks-api:latest
         docker tag dks-ui:latest ghcr.io/langbledsoe/dks-ui:latest
         docker push ghcr.io/langbledsoe/dks-api:latest
         docker push ghcr.io/langbledsoe/dks-ui:latest